import {
  Calculator,
  Chrome,
  Clock,
  Code2,
  Earth,
  FolderOpen,
  FolderOpenIcon,
  Gamepad2,
  Image,
  Lock,
  LockIcon,
  NotebookPen,
  PaintbrushIcon,
  Settings,
  Terminal,
  User2,
  Wallpaper,
} from "lucide-react";

export const iconMap = [
  { id: "notes", label: "Notes", Icon: NotebookPen },
  { id: "paint", label: "Paint", Icon: PaintbrushIcon },
  { id: "saved_notes", label: "Saved Notes", Icon: FolderOpen },
  { id: "clock", label: "Clock", Icon: Clock },
  { id: "security", label: "Security", Icon: LockIcon },
  { id: "space_explorer_game", label: "Space Game", Icon: Gamepad2 },
  { id: "portfolio", label: "My Portfolio", Icon: User2 },
  { id: "react_code_editor", label: "Code Lab", Icon: Code2 },
  { id: "calculator", label: "Calculator", Icon: Calculator },
  { id: "chitramitra", label: "ChitraMitra - Social App", Icon: Image },
  { id: "solar_system", label: "Solar System", Icon: Earth },
  { id: "terminal", label: "Terminal", Icon: Terminal },
  { id: "wallpaper", label: "Wallpaper", Icon: Wallpaper },
  { id: "setting", label: "Settings", Icon: Settings },
];
